; Footprints are 2x2 tiles each, but are stored as a 16x64-tile image
; (32 rows of 8 footprints per row).
; That means there's a row of the top two tiles for eight footprints,
; then a row of the bottom two tiles for those eight footprints.

; These macros help extract the first and the last two tiles, respectively.
DEF footprint_top    EQUS "0,                 2 * LEN_1BPP_TILE"
DEF footprint_bottom EQUS "2 * LEN_1BPP_TILE, 2 * LEN_1BPP_TILE"

Footprints:
	table_width LEN_1BPP_TILE * 4, Footprints

; 001-008
INCBIN "gfx/footprints/bulbasaur.1bpp"
INCBIN "gfx/footprints/ivysaur.1bpp"
INCBIN "gfx/footprints/venusaur.1bpp"
INCBIN "gfx/footprints/charmander.1bpp"
INCBIN "gfx/footprints/charmeleon.1bpp"
INCBIN "gfx/footprints/charizard.1bpp"
INCBIN "gfx/footprints/squirtle.1bpp"
INCBIN "gfx/footprints/wartortle.1bpp"
; 009-016
INCBIN "gfx/footprints/blastoise.1bpp"
INCBIN "gfx/footprints/caterpie.1bpp"
INCBIN "gfx/footprints/metapod.1bpp"
INCBIN "gfx/footprints/butterfree.1bpp"
INCBIN "gfx/footprints/weedle.1bpp"
INCBIN "gfx/footprints/kakuna.1bpp"
INCBIN "gfx/footprints/beedrill.1bpp"
INCBIN "gfx/footprints/pidgey.1bpp"
; 017-024 top halves
INCBIN "gfx/footprints/pidgeotto.1bpp"
INCBIN "gfx/footprints/pidgeot.1bpp"
INCBIN "gfx/footprints/rattata.1bpp"
INCBIN "gfx/footprints/raticate.1bpp"
INCBIN "gfx/footprints/spearow.1bpp"
INCBIN "gfx/footprints/fearow.1bpp"
INCBIN "gfx/footprints/ekans.1bpp"
INCBIN "gfx/footprints/arbok.1bpp"
; 025-032 top halves
INCBIN "gfx/footprints/pikachu.1bpp"
INCBIN "gfx/footprints/raichu.1bpp"
INCBIN "gfx/footprints/sandshrew.1bpp"
INCBIN "gfx/footprints/sandslash.1bpp"
INCBIN "gfx/footprints/nidoran_f.1bpp"
INCBIN "gfx/footprints/nidorina.1bpp"
INCBIN "gfx/footprints/nidoqueen.1bpp"
INCBIN "gfx/footprints/nidoran_m.1bpp"
; 033-040 top halves
INCBIN "gfx/footprints/nidorino.1bpp"
INCBIN "gfx/footprints/nidoking.1bpp"
INCBIN "gfx/footprints/clefairy.1bpp"
INCBIN "gfx/footprints/clefable.1bpp"
INCBIN "gfx/footprints/vulpix.1bpp"
INCBIN "gfx/footprints/ninetales.1bpp"
INCBIN "gfx/footprints/jigglypuff.1bpp"
INCBIN "gfx/footprints/wigglytuff.1bpp"
; 041-048 top halves
INCBIN "gfx/footprints/zubat.1bpp"
INCBIN "gfx/footprints/golbat.1bpp"
INCBIN "gfx/footprints/oddish.1bpp"
INCBIN "gfx/footprints/gloom.1bpp"
INCBIN "gfx/footprints/vileplume.1bpp"
INCBIN "gfx/footprints/paras.1bpp"
INCBIN "gfx/footprints/parasect.1bpp"
INCBIN "gfx/footprints/venonat.1bpp"
; 049-056 top halves
INCBIN "gfx/footprints/venomoth.1bpp"
INCBIN "gfx/footprints/diglett.1bpp"
INCBIN "gfx/footprints/dugtrio.1bpp"
INCBIN "gfx/footprints/meowth.1bpp"
INCBIN "gfx/footprints/persian.1bpp"
INCBIN "gfx/footprints/psyduck.1bpp"
INCBIN "gfx/footprints/golduck.1bpp"
INCBIN "gfx/footprints/mankey.1bpp"
; 057-064 top halves
INCBIN "gfx/footprints/primeape.1bpp"
INCBIN "gfx/footprints/growlithe.1bpp"
INCBIN "gfx/footprints/arcanine.1bpp"
INCBIN "gfx/footprints/poliwag.1bpp"
INCBIN "gfx/footprints/poliwhirl.1bpp"
INCBIN "gfx/footprints/poliwrath.1bpp"
INCBIN "gfx/footprints/abra.1bpp"
INCBIN "gfx/footprints/kadabra.1bpp"
; 065-072 top halves
INCBIN "gfx/footprints/alakazam.1bpp"
INCBIN "gfx/footprints/machop.1bpp"
INCBIN "gfx/footprints/machoke.1bpp"
INCBIN "gfx/footprints/machamp.1bpp"
INCBIN "gfx/footprints/bellsprout.1bpp"
INCBIN "gfx/footprints/weepinbell.1bpp"
INCBIN "gfx/footprints/victreebel.1bpp"
INCBIN "gfx/footprints/tentacool.1bpp"
; 073-080 top halves
INCBIN "gfx/footprints/tentacruel.1bpp"
INCBIN "gfx/footprints/geodude.1bpp"
INCBIN "gfx/footprints/graveler.1bpp"
INCBIN "gfx/footprints/golem.1bpp"
INCBIN "gfx/footprints/ponyta.1bpp"
INCBIN "gfx/footprints/rapidash.1bpp"
INCBIN "gfx/footprints/slowpoke.1bpp"
INCBIN "gfx/footprints/slowbro.1bpp"
; 081-088 top halves
INCBIN "gfx/footprints/magnemite.1bpp"
INCBIN "gfx/footprints/magneton.1bpp"
INCBIN "gfx/footprints/farfetch_d.1bpp"
INCBIN "gfx/footprints/doduo.1bpp"
INCBIN "gfx/footprints/dodrio.1bpp"
INCBIN "gfx/footprints/seel.1bpp"
INCBIN "gfx/footprints/dewgong.1bpp"
INCBIN "gfx/footprints/grimer.1bpp"
; 089-096 top halves
INCBIN "gfx/footprints/muk.1bpp"
INCBIN "gfx/footprints/shellder.1bpp"
INCBIN "gfx/footprints/cloyster.1bpp"
INCBIN "gfx/footprints/gastly.1bpp"
INCBIN "gfx/footprints/haunter.1bpp"
INCBIN "gfx/footprints/gengar.1bpp"
INCBIN "gfx/footprints/onix.1bpp"
INCBIN "gfx/footprints/drowzee.1bpp"
; 097-104 top halves
INCBIN "gfx/footprints/hypno.1bpp"
INCBIN "gfx/footprints/krabby.1bpp"
INCBIN "gfx/footprints/kingler.1bpp"
INCBIN "gfx/footprints/voltorb.1bpp"
INCBIN "gfx/footprints/electrode.1bpp"
INCBIN "gfx/footprints/exeggcute.1bpp"
INCBIN "gfx/footprints/exeggutor.1bpp"
INCBIN "gfx/footprints/cubone.1bpp"
; 105-112 top halves
INCBIN "gfx/footprints/marowak.1bpp"
INCBIN "gfx/footprints/hitmonlee.1bpp"
INCBIN "gfx/footprints/hitmonchan.1bpp"
INCBIN "gfx/footprints/lickitung.1bpp"
INCBIN "gfx/footprints/koffing.1bpp"
INCBIN "gfx/footprints/weezing.1bpp"
INCBIN "gfx/footprints/rhyhorn.1bpp"
INCBIN "gfx/footprints/rhydon.1bpp"
; 113-120 top halves
INCBIN "gfx/footprints/chansey.1bpp"
INCBIN "gfx/footprints/tangela.1bpp"
INCBIN "gfx/footprints/kangaskhan.1bpp"
INCBIN "gfx/footprints/horsea.1bpp"
INCBIN "gfx/footprints/seadra.1bpp"
INCBIN "gfx/footprints/goldeen.1bpp"
INCBIN "gfx/footprints/seaking.1bpp"
INCBIN "gfx/footprints/staryu.1bpp"
; 121-128 top halves
INCBIN "gfx/footprints/starmie.1bpp"
INCBIN "gfx/footprints/mr__mime.1bpp"
INCBIN "gfx/footprints/scyther.1bpp"
INCBIN "gfx/footprints/jynx.1bpp"
INCBIN "gfx/footprints/electabuzz.1bpp"
INCBIN "gfx/footprints/magmar.1bpp"
INCBIN "gfx/footprints/pinsir.1bpp"
INCBIN "gfx/footprints/tauros.1bpp"
; 129-136 top halves
INCBIN "gfx/footprints/magikarp.1bpp"
INCBIN "gfx/footprints/gyarados.1bpp"
INCBIN "gfx/footprints/lapras.1bpp"
INCBIN "gfx/footprints/ditto.1bpp"
INCBIN "gfx/footprints/eevee.1bpp"
INCBIN "gfx/footprints/vaporeon.1bpp"
INCBIN "gfx/footprints/jolteon.1bpp"
INCBIN "gfx/footprints/flareon.1bpp"
; 137-144 top halves
INCBIN "gfx/footprints/porygon.1bpp"
INCBIN "gfx/footprints/omanyte.1bpp"
INCBIN "gfx/footprints/omastar.1bpp"
INCBIN "gfx/footprints/kabuto.1bpp"
INCBIN "gfx/footprints/kabutops.1bpp"
INCBIN "gfx/footprints/aerodactyl.1bpp"
INCBIN "gfx/footprints/snorlax.1bpp"
INCBIN "gfx/footprints/articuno.1bpp"
; 145-152 top halves
INCBIN "gfx/footprints/zapdos.1bpp"
INCBIN "gfx/footprints/moltres.1bpp"
INCBIN "gfx/footprints/dratini.1bpp"
INCBIN "gfx/footprints/dragonair.1bpp"
INCBIN "gfx/footprints/dragonite.1bpp"
INCBIN "gfx/footprints/mewtwo.1bpp"
INCBIN "gfx/footprints/mew.1bpp"
INCBIN "gfx/footprints/chikorita.1bpp"
; 153-160 top halves
INCBIN "gfx/footprints/bayleef.1bpp"
INCBIN "gfx/footprints/meganium.1bpp"
INCBIN "gfx/footprints/cyndaquil.1bpp"
INCBIN "gfx/footprints/quilava.1bpp"
INCBIN "gfx/footprints/typhlosion.1bpp"
INCBIN "gfx/footprints/totodile.1bpp"
INCBIN "gfx/footprints/croconaw.1bpp"
INCBIN "gfx/footprints/feraligatr.1bpp"
; 161-168 top halves
INCBIN "gfx/footprints/sentret.1bpp"
INCBIN "gfx/footprints/furret.1bpp"
INCBIN "gfx/footprints/hoothoot.1bpp"
INCBIN "gfx/footprints/noctowl.1bpp"
INCBIN "gfx/footprints/ledyba.1bpp"
INCBIN "gfx/footprints/ledian.1bpp"
INCBIN "gfx/footprints/spinarak.1bpp"
INCBIN "gfx/footprints/ariados.1bpp"
; 169-176 top halves
INCBIN "gfx/footprints/crobat.1bpp"
INCBIN "gfx/footprints/chinchou.1bpp"
INCBIN "gfx/footprints/lanturn.1bpp"
INCBIN "gfx/footprints/pichu.1bpp"
INCBIN "gfx/footprints/cleffa.1bpp"
INCBIN "gfx/footprints/igglybuff.1bpp"
INCBIN "gfx/footprints/togepi.1bpp"
INCBIN "gfx/footprints/togetic.1bpp"
; 177-184 top halves
INCBIN "gfx/footprints/natu.1bpp"
INCBIN "gfx/footprints/xatu.1bpp"
INCBIN "gfx/footprints/mareep.1bpp"
INCBIN "gfx/footprints/flaaffy.1bpp"
INCBIN "gfx/footprints/ampharos.1bpp"
INCBIN "gfx/footprints/bellossom.1bpp"
INCBIN "gfx/footprints/marill.1bpp"
INCBIN "gfx/footprints/azumarill.1bpp"
; 185-192 top halves
INCBIN "gfx/footprints/sudowoodo.1bpp"
INCBIN "gfx/footprints/politoed.1bpp"
INCBIN "gfx/footprints/hoppip.1bpp"
INCBIN "gfx/footprints/skiploom.1bpp"
INCBIN "gfx/footprints/jumpluff.1bpp"
INCBIN "gfx/footprints/aipom.1bpp"
INCBIN "gfx/footprints/sunkern.1bpp"
INCBIN "gfx/footprints/sunflora.1bpp"
; 193-200 top halves
INCBIN "gfx/footprints/yanma.1bpp"
INCBIN "gfx/footprints/wooper.1bpp"
INCBIN "gfx/footprints/quagsire.1bpp"
INCBIN "gfx/footprints/espeon.1bpp"
INCBIN "gfx/footprints/umbreon.1bpp"
INCBIN "gfx/footprints/murkrow.1bpp"
INCBIN "gfx/footprints/slowking.1bpp"
INCBIN "gfx/footprints/misdreavus.1bpp"
; 201-208 top halves
INCBIN "gfx/footprints/unown.1bpp"
INCBIN "gfx/footprints/wobbuffet.1bpp"
INCBIN "gfx/footprints/girafarig.1bpp"
INCBIN "gfx/footprints/pineco.1bpp"
INCBIN "gfx/footprints/forretress.1bpp"
INCBIN "gfx/footprints/dunsparce.1bpp"
INCBIN "gfx/footprints/gligar.1bpp"
INCBIN "gfx/footprints/steelix.1bpp"
; 209-216 top halves
INCBIN "gfx/footprints/snubbull.1bpp"
INCBIN "gfx/footprints/granbull.1bpp"
INCBIN "gfx/footprints/qwilfish.1bpp"
INCBIN "gfx/footprints/scizor.1bpp"
INCBIN "gfx/footprints/shuckle.1bpp"
INCBIN "gfx/footprints/heracross.1bpp"
INCBIN "gfx/footprints/sneasel.1bpp"
INCBIN "gfx/footprints/teddiursa.1bpp"
; 217-224 top halves
INCBIN "gfx/footprints/ursaring.1bpp"
INCBIN "gfx/footprints/slugma.1bpp"
INCBIN "gfx/footprints/magcargo.1bpp"
INCBIN "gfx/footprints/swinub.1bpp"
INCBIN "gfx/footprints/piloswine.1bpp"
INCBIN "gfx/footprints/corsola.1bpp"
INCBIN "gfx/footprints/remoraid.1bpp"
INCBIN "gfx/footprints/octillery.1bpp"
; 225-232 top halves
INCBIN "gfx/footprints/delibird.1bpp"
INCBIN "gfx/footprints/mantine.1bpp"
INCBIN "gfx/footprints/skarmory.1bpp"
INCBIN "gfx/footprints/houndour.1bpp"
INCBIN "gfx/footprints/houndoom.1bpp"
INCBIN "gfx/footprints/kingdra.1bpp"
INCBIN "gfx/footprints/phanpy.1bpp"
INCBIN "gfx/footprints/donphan.1bpp"
; 233-240 top halves
INCBIN "gfx/footprints/porygon2.1bpp"
INCBIN "gfx/footprints/stantler.1bpp"
INCBIN "gfx/footprints/smeargle.1bpp"
INCBIN "gfx/footprints/tyrogue.1bpp"
INCBIN "gfx/footprints/hitmontop.1bpp"
INCBIN "gfx/footprints/smoochum.1bpp"
INCBIN "gfx/footprints/elekid.1bpp"
INCBIN "gfx/footprints/magby.1bpp"
; 241-248 top halves
INCBIN "gfx/footprints/miltank.1bpp"
INCBIN "gfx/footprints/blissey.1bpp"
INCBIN "gfx/footprints/raikou.1bpp"
INCBIN "gfx/footprints/entei.1bpp"
INCBIN "gfx/footprints/suicune.1bpp"
INCBIN "gfx/footprints/larvitar.1bpp"
INCBIN "gfx/footprints/pupitar.1bpp"
INCBIN "gfx/footprints/tyranitar.1bpp"
; 249-256 top halves
INCBIN "gfx/footprints/lugia.1bpp"
INCBIN "gfx/footprints/ho_oh.1bpp"
INCBIN "gfx/footprints/celebi.1bpp"
INCBIN "gfx/footprints/252.1bpp"
INCBIN "gfx/footprints/253.1bpp"
INCBIN "gfx/footprints/254.1bpp"
INCBIN "gfx/footprints/255.1bpp"
INCBIN "gfx/footprints/256.1bpp"

	assert_table_length $100
